# Artifact Hub repository metadata
# https://artifacthub.io/docs/topics/repositories/
repositoryID: d02bce8a-6bbb-441b-9e0d-579c8a79e4dd
owners:
  - name: rvbsalgado
    email: rvbsalgado@users.noreply.github.com
