apiVersion: v2
name: fencemaster
description: Kubernetes admission controller that automatically assigns namespaces to Rancher projects
version: 0.1.13
appVersion: "1.0.0-rc.6"
home: https://github.com/rvbsalgado/fencemaster
icon: https://raw.githubusercontent.com/rvbsalgado/fencemaster/main/docs/images/logo/logo-256.png
sources:
  - https://github.com/rvbsalgado/fencemaster
keywords:
  - rancher
  - admission-controller
  - webhook
  - namespace
  - project
  - kubernetes
maintainers:
  - name: rvbsalgado
    email: rvbsalgado@users.noreply.github.com
    url: https://github.com/rvbsalgado
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: fixed
      description: Chart release pipeline
    - kind: changed
      description: Bump chart version to 0.1.6
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/rvbsalgado/fencemaster
    - name: Source
      url: https://github.com/rvbsalgado/fencemaster
