apiVersion: v2
name: fencemaster
description: Kubernetes admission controller that automatically assigns namespaces to Rancher projects
version: 0.1.2
appVersion: "1.0.0-rc.3"
home: https://github.com/rvbsalgado/fencemaster
icon: https://raw.githubusercontent.com/rvbsalgado/fencemaster/main/docs/images/logo/logo-256.png
sources:
  - https://github.com/rvbsalgado/fencemaster
keywords:
  - rancher
  - admission-controller
  - webhook
  - namespace
  - project
  - kubernetes
maintainers:
  - name: rvbsalgado
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/rvbsalgado/fencemaster
    - name: Source
      url: https://github.com/rvbsalgado/fencemaster
