{{- if and .Values.serviceAccount.create (or (eq .Values.installMode "server") (eq .Values.installMode "all")) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fencemaster.serviceAccountName" . }}
  labels:
    {{- include "fencemaster.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
